default: &default
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  database: tools-homework_development
test:
  <<: *default
  database: tools-homework_test
production:
  <<: *default
  database: tools-homework_production
